version: '3'

services:

  # NGINX proxy
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${DATA-./data}/nginx/conf.d:/etc/nginx/conf.d
      - ${DATA-./data}/nginx/vhost.d:/etc/nginx/vhost.d
      - ${DATA-./data}/nginx/html:/usr/share/nginx/html
      - ${DATA-./data}/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # Let's encrypt
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    hostname: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    volumes:
      - ${DATA-./data}/nginx/conf.d:/etc/nginx/conf.d
      - ${DATA-./data}/nginx/vhost.d:/etc/nginx/vhost.d
      - ${DATA-./data}/nginx/html:/usr/share/nginx/html
      - ${DATA-./data}/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # MySQL
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql
    hostname: ${MYSQL_HOST-mysql}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-changeme}
    ports:
      - '127.0.1.100:3306:3306'
    volumes:
      - ${DATA-./data}/mysql:/var/lib/mysql

  # MySQL (master)
  master:
    build: ./images/mysql
    container_name: master
    hostname: master
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-changeme}
      - MYSQL_REPLICATION=master
      - MYSQL_SERVER_ID=1
    ports:
      - '127.0.2.100:3306:3306'
    volumes:
      - ${DATA-./data}/master:/var/lib/mysql

  # MySQL (slave)
  slave:
    build: ./images/mysql
    container_name: slave
    hostname: slave
    restart: always
    depends_on:
      - master
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-changeme}
      - MYSQL_REPLICATION=slave
      - MYSQL_SERVER_ID=2
      - MYSQL_MASTER_HOST=master
    ports:
      - '127.0.3.100:3306:3306'
    volumes:
      - ${DATA-./data}/slave:/var/lib/mysql

  # Apache2
  apache2:
    build: ./images/apache2
    container_name: apache2
    hostname: apache2
    restart: always
    environment:
      - TLD=${TLD-dev}
      - VIRTUAL_HOST=*.${TLD}
      - XDEBUG_ENABLE=${XDEBUG_ENABLE-no}
      - SMTP_RELAY=${SMTP_RELAY}
    volumes:
      - ${DATA-./data}/html:/var/www/html
      - ${DATA-./data}/xdebug:/tmp/xdebug

  # Portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    ports:
      - '9090:9000'
    volumes:
      - ${DATA-./data}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
